import{i as a,S as b,a as L}from"./assets/vendor-Qob_5Ba8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const S="46331793-9cec4180ce0cddf1fbb8fc669",w="https://pixabay.com/api/",v=document.querySelector("#search-form"),n=document.querySelector("#gallery"),E=document.querySelector("#loader"),i=document.querySelector("#load-more");let h,c=1,d="",m=0;v.addEventListener("submit",$);i.addEventListener("click",g);async function $(t){if(t.preventDefault(),d=t.target.querySelector("#search-input").value.trim(),d===""){a.error({title:"Error",message:"Please enter a search term!"});return}P(),c=1,f(),i.classList.add("hidden");try{const o=await g();o.hits.length===0?a.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}):(p(o.hits),h=new b(".gallery a",{captionsData:"alt",captionDelay:250}),m=o.totalHits,y())}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{f()}}async function g(){try{const{data:t}=await L.get(`${w}?key=${S}&q=${d}&image_type=photo&orientation=horizontal&safesearch=true&page=${c}&per_page=40`);return p(t.hits),h.refresh(),c+=1,y(),q(),t}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later."})}}function y(){n.querySelectorAll(".gallery__item").length>=m?(i.classList.add("hidden"),a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})):i.classList.remove("hidden")}function p(t){const o=t.map(s=>`
    <a href="${s.largeImageURL}" class="gallery__item">
      <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${s.likes}</p>
        <p><b>Views:</b> ${s.views}</p>
        <p><b>Comments:</b> ${s.comments}</p>
        <p><b>Downloads:</b> ${s.downloads}</p>
      </div>
    </a>
  `).join("");n.insertAdjacentHTML("beforeend",o)}function P(){n.innerHTML=""}function f(){E.classList.toggle("hidden")}function q(){const{height:t}=n.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
