import{i as u,a as g,S as h}from"./assets/vendor-BIHATn4Y.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(e){if(e.ep)return;e.ep=!0;const a=s(e);fetch(e.href,a)}})();const b="46331793-9cec4180ce0cddf1fbb8fc669",L=document.querySelector(".search-form"),c=document.querySelector("#gallery"),d=document.querySelector("#loader"),n=document.createElement("button");n.textContent="Load more";n.classList.add("load-more");document.body.append(n);n.style.display="none";let m="",r=1,f=40,p;async function v(t,o){const s=`https://pixabay.com/api/?key=${b}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${f}`;try{d.style.display="block";const i=await g.get(s);return d.style.display="none",i.data}catch(i){return console.error("Błąd w zapytaniu:",i),d.style.display="none",u.error({title:"Error",message:"Problem with fetching images"}),{hits:[],totalHits:0}}}function w(t){r===1&&(c.innerHTML="",c.classList.remove("hidden"));const o=t.map(s=>`
    <a href="${s.largeImageURL}" class="gallery-item">
      <img src="${s.webformatURL}" alt="${s.tags}" />
      <div class="image-info">
        <p><span class="image-info-label">Likes:</span> <span class="image-info-value">${s.likes}</span></p>
        <p><span class="image-info-label">Views:</span> <span class="image-info-value">${s.views}</span></p>
        <p><span class="image-info-label">Comments:</span> <span class="image-info-value">${s.comments}</span></p>
        <p><span class="image-info-label">Downloads:</span> <span class="image-info-value">${s.downloads}</span></p>
      </div>
    </a>
  `).join("");c.insertAdjacentHTML("beforeend",o),p?p.refresh():p=new h(".gallery-item",{captionsData:"alt",captionDelay:250})}async function y(){const t=await v(m,r);if(t.hits.length===0&&r===1){u.info({iconUrl:"./src/img/no-images-icon.png",message:"Sorry, there are no images matching your search query. Please, try again!",backgroundColor:"#EF4040"}),n.style.display="none";return}if(w(t.hits),t.hits.length<f||r*f>=t.totalHits?(n.style.display="none",u.info({message:"We're sorry, but you've reached the end of search results."})):n.style.display="block",r>1){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}L.addEventListener("submit",async t=>{t.preventDefault(),m=document.querySelector("#query").value.trim(),m&&(r=1,n.style.display="none",await y())});n.addEventListener("click",async()=>{r+=1,await y()});
//# sourceMappingURL=index.js.map
