/* empty css                      */import{i as a,S as b,a as w}from"./assets/vendor-Qob_5Ba8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const v="46331793-9cec4180ce0cddf1fbb8fc669",S="https://pixabay.com/api/",q=document.querySelector("#search-form"),f=document.querySelector("#gallery"),h=document.querySelector("#loader"),n=document.querySelector("#load-more");let u,m="",l=1;const p=40;let y=0;q.addEventListener("submit",E);n.addEventListener("click",P);async function E(r){if(r.preventDefault(),m=r.target.querySelector("#search-input").value.trim(),m===""){a.error({title:"Error",message:"Please enter a search term!"});return}$(),c(!0),n.classList.add("hidden"),l=1;try{const{data:t}=await g();y=t.totalHits,t.hits.length===0?a.warning({title:"No results",message:"No images found. Try a different search query!"}):(L(t.hits),u=new b(".gallery a",{captionsData:"alt",captionDelay:250}),u.refresh(),t.totalHits>p&&n.classList.remove("hidden"))}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{c(!1)}}async function P(){l+=1,c(!0);try{const{data:r}=await g();L(r.hits,!0),u.refresh();const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),l*p>=y&&(n.classList.add("hidden"),a.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Failed to load more images. Please try again later."})}finally{c(!1)}}async function g(){return await w.get(`${S}`,{params:{key:v,q:m,image_type:"photo",orientation:"horizontal",safesearch:!0,page:l,per_page:p}})}function L(r,t=!1){const i=r.map(s=>`
      <a href="${s.largeImageURL}" class="gallery__item">
        <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${s.likes}</p>
          <p><b>Views:</b> ${s.views}</p>
          <p><b>Comments:</b> ${s.comments}</p>
          <p><b>Downloads:</b> ${s.downloads}</p>
        </div>
      </a>
    `).join("");t?f.insertAdjacentHTML("beforeend",i):f.innerHTML=i}function $(){f.innerHTML=""}function c(r){r?h.classList.remove("hidden"):h.classList.add("hidden")}
//# sourceMappingURL=index.js.map
